"""Reflectance analysis: average grey level over time in img sequence."""

# Non-standard modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import imgbasics

# Local imports
from .analysis_base import Analysis
from .formatters import PandasFormatter
from .results import PandasTsvJsonResults
from ..parameters.analysis import Zones
from ..viewers import AnalysisViewer


# ======================= Plotting / Animation classes =======================


class GreyLevelViewer(AnalysisViewer):

    def _create_figure(self):
        self.fig = plt.figure(figsize=(5, 7))
        xmin = 0.1
        xmax = 0.9
        w = xmax - xmin
        self.ax_img = self.fig.add_axes([xmin, 0.33, w, 0.65])
        self.ax_analysis = self.fig.add_axes([xmin, 0.09, w, 0.25])
        self.axs = self.ax_img, self.ax_analysis
        self.ax_img.axis('off')

    def _create_image(self, data):
        self.ax_img.set_title(f"img #{data['num']}")
        self.imshow = self.analysis.img_series._imshow(
            data["image"],
            ax=self.ax_img,
            **self.kwargs,
        )

    def _update_image(self, data):
        self.ax_img.set_title(f"img #{data['num']}")
        self.imshow.set_array(data['image'])

    def _autoscale(self):
        self.ax_analysis.relim()  # without this, axes limits change don't work
        self.ax_analysis.autoscale(axis='both')

    def _first_plot(self, data):
        """What to do the first time data arrives on the plot."""
        glevels = data.get('glevels', None)

        self._create_image(data)

        self.analysis_results_available = (self.analysis.results.data is not None)

        self.curves = []
        self.pts = []
        self.bar = self.ax_analysis.axvline(x=data['num'], c='gray')
        self.zone_names = list(self.analysis.zones.data)

        for i, zone_name in enumerate(self.zone_names):

            if self.analysis_results_available:  # existing or re-generated
                analysis_nums = self.analysis.results.data.index
                analysis_data = self.analysis.results.data[zone_name]
            else:
                analysis_nums = []
                analysis_data = []

            curve, = self.ax_analysis.plot(
                analysis_nums,
                analysis_data,
                '.',
                label=zone_name,
                alpha=0.5,
            )
            color = curve.get_color()

            if glevels is not None:
                pt_num = data['num']
                pt_glevel = glevels[i]
            else:
                pt_num = []
                pt_glevel = []

            pt, = self.ax_analysis.plot(pt_num, pt_glevel, 'o', c=color)

            self.curves.append(curve)
            self.pts.append(pt)

            zone = self.analysis.zones.data[zone_name]
            imgbasics.cropping._cropzone_draw(self.ax_img, zone, c=color)

        self.ax_analysis.legend()
        self.ax_analysis.grid()

        self.updated_artists = self.pts + [self.imshow, self.bar]

    def _update_plot(self, data):
        """What to do upon iterations of the plot after the first time."""
        num = data['num']
        glevels = data.get('glevels', None)

        self._update_image(data)
        self.bar.set_xdata(num)

        if glevels is None:
            return

        for zname, pt, curve, glevel in zip(
            self.zone_names,
            self.pts,
            self.curves,
            glevels,
        ):
            pt.set_data((num, glevel))

            if self.analysis_results_available:
                continue

            # If results data not available (e.g. during live analysis)
            # then use the data from the current analysis
            analysis_data = self.analysis.formatter.data
            curve.set_data(analysis_data['num'], analysis_data[zname])

        self._autoscale()


class GreyLevelFormatter_Pandas(PandasFormatter):

    def _prepare_data_storage(self):
        """Prepare structure(s) that will hold the analyzed data."""
        # 'zone 1', 'zone 2', etc.
        self.zone_names = list(self.analysis.zones.data)

        # Init dictionary with column names as keys, empty lists will be filled
        self.data = {'num': []}
        for zone_name in self.zone_names:
            self.data[zone_name] = []

    def _store_data(self, data):
        """How to store data generated by analysis on a single image."""
        num = data['num']

        # Doing two times the same analysis (e.g. when using inspect(live=True)
        # Should return the same result, so this case is simply ignored)
        if num in self.data['num']:
            return

        self.data['num'].append(num)
        for zone_name, glevel in zip(self.zone_names, data['glevels']):
            self.data[zone_name].append(glevel)

    def _to_pandas(self):
        """How to convert data generated by _store_data() into a pandas table."""
        return pd.DataFrame(self.data).sort_values('num')

    def _regenerate_data(self, num):
        """How to go back to raw dict of data from results.data ('num' added later)"""
        if self.analysis.results.data is None:  # analysis not run or reset
            return {}

        glevel_data = self.analysis.results.data.filter(like='zone')

        try:
            glevels = glevel_data.loc[num]
        except KeyError:    # Analysis not made for the specific num
            return {}

        return {'glevels': list(glevels)}


class GreyLevelResults_PandasTsv(PandasTsvJsonResults):

    measurement_type = 'glevel'
    default_filename = 'Img_GreyLevel'


# =========================== Main ANALYSIS class ============================


class GreyLevel(Analysis):
    """Class to perform analysis of average grey level on image series."""

    measurement_type = 'glevel'

    DefaultViewer = GreyLevelViewer
    DefaultFormatter = GreyLevelFormatter_Pandas
    DefaultResults = GreyLevelResults_PandasTsv

    def __init__(
        self,
        img_series,
        savepath=None,
        func=np.mean,
        Viewer=None,
        Formatter=None,
        Results=None,
    ):
        """Analysis of avg gray level on selected zone in series of images.

        img_series : ImgSeries or ImgStack object
            image series on which the analysis will be run

        savepath : str or Path object
            folder in which to save analysis data & metadata
                    (if not specified, the img_series savepath is used)

        func : function
            function to be applied on the image pixels in the defined
            analysis zones (default: np.mean). Other typical functions
            can be: np.sum, np.max, etc.

        Viewer : class
            (subclass of AnalysisViewer)
            Viewer class/subclasses that is used to display and inspect
            analysis data (is used by ViewerTools)

        Formatter: class
            (subclass of Formatter)
            class used to format results spit out by the raw analysis into
            something storable/saveable by the Results class.

        Results : class
            (subclass of Results)
            Results class/subclasses that is used to store, save and load
            analysis data and metadata.
        """
        super().__init__(
            img_series=img_series,
            savepath=savepath,
            Viewer=Viewer,
            Formatter=Formatter,
            Results=Results,
        )

        # empty zones object, if not filled with zones.define() or
        # zones.load() prior to starting analysis with self.run(),
        # the whole image is considered
        self.zones = Zones(self)
        self.func = func

    def _analyze(self, img, details=False):
        """Analysis process on single image. Must return a dict.

        Parameters
        ----------
        img : array_like
            image array to be analyzed (e.g. numpy array).

        details : bool
            whether to include more details (e.g. for debugging or live view)


        Returns
        -------
        dict
            dict of data, handled by formatter._store_data()
        """
        glevels = []

        for cropzone in self.zones.data.values():
            img_crop = imgbasics.imcrop(img, cropzone)
            glevel = self.func(img_crop)
            glevels.append(glevel)

        data = {'glevels': glevels}

        return data

    def _init_analysis(self):
        """Check everything OK before starting analysis & initialize params."""
        if self.zones.is_empty:
            self._set_default_zone()

    def _set_default_zone(self):
        print('Warning: no zones defined; taking full image as default.')
        default_crop = 0, 0, self.img_series.nx, self.img_series.ny
        self.zones.data = {'zone 1': default_crop}

    def _add_metadata(self):
        """Add useful analysis parameters etc. to the self.metadata dict.

        (later saved in the metadata json file)
        Define in subclasses
        """
        self.results.metadata['zones'] = self.zones.data

        func_info = f'{self.func.__module__}.{self.func.__name__}'
        self.results.metadata['function'] = func_info

    def regenerate(self, filename=None):
        """Load saved data, metadata and regenerate objects from them.

        Is used to reset the system in a state similar to the end of the
        analysis that was made before saving the results.

        Parameters
        ----------
        filename : str
            name of the analysis results file (if None, use default)

        Notes
        -----
            More or less equivalent to:
            >>> analysis.results.load(filename=filename)
            >>> image_series.load_transforms()
            (except that transforms are loaded from the metadata file of the
            analysis, not from a file generated by
            image_series.save_transforms())
        """

        # Load data
        super().regenerate(filename=filename)

        # regenerate internal zones object
        self.zones.load(filename=filename)
