"""Reflectance analysis: average grey level over time in img sequence."""

# Non-standard modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import imgbasics

# Local imports
from .analysis_base import Analysis
from .formatters import PandasFormatter
from .results import PandasTsvJsonResults
from ..parameters.analysis import Zones
from ..viewers import AnalysisViewer


# ======================= Plotting / Animation classes =======================


class GreyLevelViewer(AnalysisViewer):

    def _create_figure(self):
        self.fig = plt.figure(figsize=(5, 7))
        xmin = 0.1
        xmax = 0.9
        w = xmax - xmin
        self.ax_img = self.fig.add_axes([xmin, 0.33, w, 0.65])
        self.ax_analysis = self.fig.add_axes([xmin, 0.09, w, 0.25])
        self.axs = self.ax_img, self.ax_analysis
        self.ax_img.axis('off')

    def _create_image(self, data):
        self.ax_img.set_title(f"img #{data['num']}")
        self.imshow = self.analysis.img_series._imshow(
            data["image"],
            ax=self.ax_img,
            **self.kwargs,
        )

    def _update_image(self, data):
        self.ax_img.set_title(f"img #{data['num']}")
        self.imshow.set_array(data['image'])

    def _get_color(self):
        """This is a hack to get automatic colors"""
        noline, = self.ax_analysis.plot([], [])
        return noline.get_color()

    def _first_plot(self, data):
        """What to do the first time data arrives on the plot."""
        # Can be None when regenerating data and analysis not made for the
        # specific num
        glevels = data.get('glevels', None)

        self._create_image(data)

        self.current_pts = []
        self.live_pts = []
        self.bar = self.ax_analysis.axvline(x=data['num'], c='gray', alpha=0.5)
        self.zone_names = list(self.analysis.zones.data)

        for i, zone_name in enumerate(self.zone_names):

            color = self._get_color()

            # If existing results from previous analysis, show them as lines
            # The lines are static and are not modified later
            if self.analysis.results.data is not None:
                self.ax_analysis.plot(
                    self.analysis.results.data.index,
                    self.analysis.results.data[zone_name],
                    c=color,
                    alpha=0.5,
                )

            # If live, new analysis will be added as persisting dots
            # (not plotted on  first plot, but plotted from formatter data
            # during the animation / inspection)
            if self.live:
                live_pts, = self.ax_analysis.plot([], [], '.', c=color, alpha=0.5)
                self.live_pts.append(live_pts)

            # In any case, manage the incoming data, keeping in mind that
            # if data is re-generated from existing results, it might not be
            # available for the specific num and glevels can be None
            if glevels is not None:
                num = data['num']
                glevel = glevels[i]
            else:
                num = []
                glevel = []

            pt, = self.ax_analysis.plot(num, glevel, 'o', c=color, label=zone_name)
            self.current_pts.append(pt)

            # Plot cropzone on image
            zone = self.analysis.zones.data[zone_name]
            imgbasics.cropping._cropzone_draw(self.ax_img, zone, c=color)

        self.ax_analysis.legend()
        self.ax_analysis.grid()

        all_pts = self.current_pts + self.live_pts
        self.updated_artists = all_pts + [self.imshow, self.bar]

    def _update_plot(self, data):
        """What to do upon iterations of the plot after the first time."""
        num = data['num']
        glevels = data.get('glevels', None)

        self._update_image(data)
        self.bar.set_xdata(num)

        if glevels is None:
            return

        for zname, pt, glevel in zip(self.zone_names, self.current_pts, glevels):
            pt.set_data((num, glevel))

        if self.live:
            analysis_data = self.analysis.formatter.data
            for zname, live_pts in zip(self.zone_names, self.live_pts):
                live_pts.set_data(analysis_data.index, analysis_data[zname])

        self._autoscale(ax=self.ax_analysis)


class GreyLevelFormatter_Pandas(PandasFormatter):

    def _prepare_data_storage(self):
        """Prepare structure(s) that will hold the analyzed data."""
        self.data = pd.DataFrame(columns=self.analysis.zones.data)
        self.data.index.name = 'num'

    def _store_data(self, data):
        """How to store data generated by analysis on a single image."""
        num = data['num']

        # Doing two times the same analysis (e.g. when using inspect(live=True)
        # Should return the same result, so this case is simply ignored)
        if num in self.data.index:
            return

        self.data.loc[num] = data['glevels']

    def _to_pandas(self):
        """How to convert data generated by _store_data() into a pandas table."""
        return pd.DataFrame(self.data).sort_index()

    def _regenerate_data(self, num):
        """How to go back to raw dict of data from results.data ('num' added later)"""
        if self.analysis.results.data is None:  # analysis not run or reset
            return {}

        glevel_data = self.analysis.results.data.filter(like='zone')

        try:
            glevels = glevel_data.loc[num]
        except KeyError:    # Analysis not made for the specific num
            return {}

        return {'glevels': list(glevels)}


class GreyLevelResults_PandasTsv(PandasTsvJsonResults):

    measurement_type = 'glevel'
    default_filename = 'Img_GreyLevel'


# =========================== Main ANALYSIS class ============================


class GreyLevel(Analysis):
    """Class to perform analysis of average grey level on image series."""

    measurement_type = 'glevel'

    DefaultViewer = GreyLevelViewer
    DefaultFormatter = GreyLevelFormatter_Pandas
    DefaultResults = GreyLevelResults_PandasTsv

    def __init__(
        self,
        img_series,
        savepath=None,
        func=np.mean,
        Viewer=None,
        Formatter=None,
        Results=None,
    ):
        """Analysis of avg gray level on selected zone in series of images.

        img_series : ImgSeries or ImgStack object
            image series on which the analysis will be run

        savepath : str or Path object
            folder in which to save analysis data & metadata
                    (if not specified, the img_series savepath is used)

        func : function
            function to be applied on the image pixels in the defined
            analysis zones (default: np.mean). Other typical functions
            can be: np.sum, np.max, etc.

        Viewer : class
            (subclass of AnalysisViewer)
            Viewer class/subclasses that is used to display and inspect
            analysis data (is used by ViewerTools)

        Formatter: class
            (subclass of Formatter)
            class used to format results spit out by the raw analysis into
            something storable/saveable by the Results class.

        Results : class
            (subclass of Results)
            Results class/subclasses that is used to store, save and load
            analysis data and metadata.
        """
        super().__init__(
            img_series=img_series,
            savepath=savepath,
            Viewer=Viewer,
            Formatter=Formatter,
            Results=Results,
        )

        # empty zones object, if not filled with zones.define() or
        # zones.load() prior to starting analysis with self.run(),
        # the whole image is considered
        self.zones = Zones(self)
        self.func = func

    def _analyze(self, img, details=False):
        """Analysis process on single image. Must return a dict.

        Parameters
        ----------
        img : array_like
            image array to be analyzed (e.g. numpy array).

        details : bool
            whether to include more details (e.g. for debugging or live view)


        Returns
        -------
        dict
            dict of data, handled by formatter._store_data()
        """
        glevels = []

        for cropzone in self.zones.data.values():
            img_crop = imgbasics.imcrop(img, cropzone)
            glevel = self.func(img_crop)
            glevels.append(glevel)

        data = {'glevels': glevels}

        return data

    def _init_analysis(self):
        """Check everything OK before starting analysis & initialize params."""
        if self.zones.is_empty:
            self._set_default_zone()

    def _set_default_zone(self):
        print('Warning: no zones defined; taking full image as default.')
        default_crop = 0, 0, self.img_series.nx, self.img_series.ny
        self.zones.data = {'zone 1': default_crop}

    def _add_metadata(self):
        """Add useful analysis parameters etc. to the self.metadata dict.

        (later saved in the metadata json file)
        Define in subclasses
        """
        self.results.metadata['zones'] = self.zones.data

        func_info = f'{self.func.__module__}.{self.func.__name__}'
        self.results.metadata['function'] = func_info

    def regenerate(self, filename=None):
        """Load saved data, metadata and regenerate objects from them.

        Is used to reset the system in a state similar to the end of the
        analysis that was made before saving the results.

        Parameters
        ----------
        filename : str
            name of the analysis results file (if None, use default)

        Notes
        -----
            More or less equivalent to:
            >>> analysis.results.load(filename=filename)
            >>> image_series.load_transforms()
            (except that transforms are loaded from the metadata file of the
            analysis, not from a file generated by
            image_series.save_transforms())
        """

        # Load data
        super().regenerate(filename=filename)

        # regenerate internal zones object
        self.zones.load(filename=filename)
